[package]
name = "go2_parallel_rl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }
rne_locomotion = { workspace = true }
rne_math = { workspace = true }
rne_physics = { workspace = true }

[[example]]
name = "136_go2_parallel_rl"
path = "main.rs"
