[package]
name = "kick_comparison"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
sha2.workspace = true
png = { workspace = true }
rne_ai = { workspace = true }
rne_core = { workspace = true }
rne_math = { workspace = true }
rne_physics = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true }
rne_robot = { workspace = true }
rne_world = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[example]]
name = "139_kick_comparison"
path = "main.rs"
