#!/usr/bin/env python3
"""Derive kick fixtures with tiny frame inertials and a legal initial Go2 stance."""

import hashlib
import json
import re
from pathlib import Path
import xml.etree.ElementTree as ET


MARKER_MASS_KG = 1e-9
MARKER_INERTIA_KG_M2 = 1e-12


def derive(source, initial_offsets=None):
    original = source.read_text()
    markers = []

    def normalize(match):
        block = match.group(0)
        link = ET.fromstring(block)
        inertial = link.find("inertial")
        if inertial is not None and float(inertial.find("mass").get("value")) > 0:
            return block
        markers.append(link.get("name"))
        properties = (
            '\n    <inertial>\n      <origin xyz="0 0 0" rpy="0 0 0"/>\n'
            f'      <mass value="{MARKER_MASS_KG}"/>\n'
            f'      <inertia ixx="{MARKER_INERTIA_KG_M2}" ixy="0" ixz="0" '
            f'iyy="{MARKER_INERTIA_KG_M2}" iyz="0" izz="{MARKER_INERTIA_KG_M2}"/>\n'
            '    </inertial>'
        )
        if inertial is not None:
            return re.sub(r"\s*<inertial>.*?</inertial>", properties, block, count=1, flags=re.S)
        end = block.index(">") + 1
        return block[:end] + properties + block[end:]

    # Commented-out links are provenance, not physical model entities.
    result = "".join(part if part.startswith("<!--") else
                     re.sub(r"<link\b[^>]*>.*?</link>", normalize, part, flags=re.S)
                     for part in re.split(r"(<!--.*?-->)", original, flags=re.S))
    initial_offsets = initial_offsets or {}

    def recenter_joint(match):
        block = match.group(0)
        joint = ET.fromstring(block)
        offset = initial_offsets.get(joint.get("name"), 0.0)
        if offset == 0.0:
            return block
        # All affected Go2 joints rotate about Y after an identity origin.
        # q_physical = q_sim + offset preserves geometry and every limit.
        if joint.find("axis").get("xyz").split() != ["0", "1", "0"]:
            raise ValueError("Unexpected axis in initial-stance joint")
        if any(float(value) != 0.0 for value in joint.find("origin").get("rpy", "0 0 0").split()):
            raise ValueError("Unexpected origin rotation in initial-stance joint")
        origin = re.search(r"<origin\b[^>]*/>", block).group(0)
        block = block.replace(origin, re.sub(r'rpy="[^"]*"', f'rpy="0 {offset} 0"', origin), 1)
        limit = re.search(r"<limit\b[^>]*/>", block).group(0)
        for name in ["lower", "upper"]:
            value = float(joint.find("limit").get(name)) - offset
            limit = re.sub(name + r'="[^"]*"', f'{name}="{value:.12g}"', limit)
        return re.sub(r"<limit\b[^>]*/>", lambda _: limit, block, count=1)

    result = "".join(part if part.startswith("<!--") else
                     re.sub(r"<joint\b[^>]*>.*?</joint>", recenter_joint, part, flags=re.S)
                     for part in re.split(r"(<!--.*?-->)", result, flags=re.S))
    result = result.replace("<robot ", '<!-- Generated by examples/139_kick_comparison/prepare_models.py.\n'
                            'Positive declared inertials are preserved. Frame inertials are regularized.\n'
                            'Go2 joint coordinates start in a legal stance; models.json records physical offsets. -->\n<robot ', 1)
    output = source.with_name(source.stem + ".kick.urdf")
    output.write_text(result)
    mass = sum(float(link.find("inertial/mass").get("value"))
               for link in ET.fromstring(result).findall("link"))
    return {"source": str(source.relative_to(REPO)), "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
            "derived": str(output.relative_to(REPO)), "derived_sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
            "regularized_frames": markers, "marker_mass_kg": MARKER_MASS_KG,
            "marker_inertia_kg_m2": MARKER_INERTIA_KG_M2, "declared_total_mass_kg": mass,
            "physical_angle_offset_rad": initial_offsets}


REPO = Path(__file__).resolve().parents[2]


def main():
    offsets = {f"{leg}_{joint}_joint": angle for leg in ["FL", "FR", "RL", "RR"]
               for joint, angle in [("thigh", 0.8), ("calf", -1.5)]}
    models = [derive(REPO / "assets/robots/go2_description/go2_description.rne.urdf", offsets),
              derive(REPO / "assets/robots/g1_description/g1_23dof.urdf")]
    (Path(__file__).parent / "models.json").write_text(json.dumps({"models": models}, indent=2) + "\n")
    print(json.dumps(models, indent=2))


if __name__ == "__main__":
    main()
